#!/usr/bin/bash


#transcriptome assembly using paired end reads
#execute as:
#trinity.sh <memory> <cpu>
memory=$1
cpu=$2

#list of read1 and read2
read1=($(ls *_1.fastq.gz));
read2=($(ls *_2.fastq.gz));

read1=$(echo ${read1[@]} | sed 's/ /,/g')
read2=$(echo ${read2[@]} | sed 's/ /,/g')


#trinity run
Trinity\
 --seqType fq\
 --max_memory ${memory}\
 --left ${read1[@]}
 --right ${read2[@]}
 --CPU ${cpu}
 --output Trinity_assembly
